DROP TABLE IF EXISTS ROLES CASCADE;

DROP TABLE IF EXISTS USERS CASCADE;

DROP TABLE IF EXISTS SPECIALTIES CASCADE;

DROP TABLE IF EXISTS APPOINTMENTS CASCADE;

DROP TABLE IF EXISTS SPECIALTIES_AND_APPOINTMENTS CASCADE;

DROP TABLE IF EXISTS HISTORIES CASCADE;

CREATE TABLE IF NOT EXISTS ROLES (
	PK_ROL SERIAL PRIMARY KEY NOT NULL,
	ROL VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS USERS (
	PK_USER SERIAL PRIMARY KEY NOT NULL,
	NAME VARCHAR(25) NOT NULL,
	LASTNAME VARCHAR(25) NOT NULL,
	AGE INTEGER NOT NULL,
	EMAIL VARCHAR(255) UNIQUE NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	DNI VARCHAR(100) UNIQUE NOT NULL,
	PICTURE TEXT,
	PHONE VARCHAR(20) UNIQUE NOT NULL,
	FK_ROL BIGINT REFERENCES ROLES (PK_ROL) NOT NULL,
	SPECIALTY VARCHAR(25) CONSTRAINT IS_DOCTOR CHECK (
		FK_ROL = 2
		OR SPECIALTY IS NULL
	)
);

CREATE TABLE IF NOT EXISTS SPECIALTIES (
	PK_SPECIALTY SERIAL PRIMARY KEY NOT NULL,
	SPECIALTY VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS APPOINTMENTS (
	PK_APPOINTMENT SERIAL PRIMARY KEY,
	FK_USER BIGINT REFERENCES USERS (PK_USER),
	REGISTRATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	APPOINTMENT_DATE DATE,
	HOUR_APPOINTMENT TIME,
	IS_CANCELLED BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS SPECIALTIES_AND_APPOINTMENTS (
	PK_SPECIALTY_AND_APPOINTMENT SERIAL PRIMARY KEY,
	FK_SPECIALTY BIGINT REFERENCES SPECIALTIES (PK_SPECIALTY) NOT NULL,
	FK_APPOINTMENT BIGINT REFERENCES APPOINTMENTS (PK_APPOINTMENT) NOT NULL,
	UNIQUE (FK_SPECIALTY, FK_APPOINTMENT)
);

CREATE TABLE IF NOT EXISTS HISTORIES (
	PK_HISTORY SERIAL PRIMARY KEY NOT NULL,
	FK_USER BIGINT REFERENCES USERS (PK_USER),
	FK_APPOINTMENT BIGINT REFERENCES APPOINTMENTS (PK_APPOINTMENT),
	DESCRIPTION TEXT NOT NULL,
	RECIPE TEXT NOT NULL,
	DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO
	ROLES (ROL)
VALUES
	('PACIENTE'),
	('DOCTOR'),
	('ADMINISTRADOR');
